<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{
    public function run()
    {
        $i = 1;
        $permissions = [
            [
                'id'    => $i++,
                'title' => 'user_management_access',
                'type' => 'role.user.user_alert.audit_log',
                'parent' => 1,
            ], 
            [
                'id'    => $i++,
                'title' => 'role_create',
                'type' => 'role',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'role_edit',
                'type' => 'role',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'role_show',
                'type' => 'role',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'role_delete',
                'type' => 'role',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'role_access',
                'type' => 'role',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'user_create',
                'type' => 'user',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'user_edit',
                'type' => 'user',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'user_show',
                'type' => 'user',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'user_delete',
                'type' => 'user',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'user_access',
                'type' => 'user',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'audit_log_show',
                'type' => 'audit_log',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'audit_log_access',
                'type' => 'audit_log',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_management_access',
                'type' => 'task_status.task_tag.task.tasks_calendar',
                'parent' => 1,
            ],
            [
                'id'    => $i++,
                'title' => 'task_status_create',
                'type' => 'task_status',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_status_edit',
                'type' => 'task_status',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_status_show',
                'type' => 'task_status',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_status_delete',
                'type' => 'task_status',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_status_access',
                'type' => 'task_status',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_tag_create',
                'type' => 'task_tag',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_tag_edit',
                'type' => 'task_tag',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_tag_show',
                'type' => 'task_tag',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_tag_delete',
                'type' => 'task_tag',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_tag_access',
                'type' => 'task_tag',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_create',
                'type' => 'task',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_edit',
                'type' => 'task',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_show',
                'type' => 'task',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_delete',
                'type' => 'task',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_access',
                'type' => 'task',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'tasks_calendar_access',
                'type' => 'tasks_calendar',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'user_alert_create',
                'type' => 'user_alert',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'user_alert_show',
                'type' => 'user_alert',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'user_alert_delete',
                'type' => 'user_alert',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'user_alert_access',
                'type' => 'user_alert',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipts_managment_access',
                'type' => 'receipt_social.receipt_social_product.receipt_client.receipt_client_product.receipt_company.receipt_outgoing.receipt_outgoing_product.banned_phone.excel_file.receipt_price_view.receipt_price_view_product',
                'parent' => 1,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_social_create',
                'type' => 'receipt_social',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_social_edit',
                'type' => 'receipt_social',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_social_show',
                'type' => 'receipt_social',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_social_delete',
                'type' => 'receipt_social',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_social_access',
                'type' => 'receipt_social',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_social_restore',
                'type' => 'receipt_social',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_social_print',
                'type' => 'receipt_social',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_social_duplicate',
                'type' => 'receipt_social',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_social_receive_money',
                'type' => 'receipt_social',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_social_product_create',
                'type' => 'receipt_social_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_social_product_edit',
                'type' => 'receipt_social_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_social_product_show',
                'type' => 'receipt_social_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_social_product_delete',
                'type' => 'receipt_social_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_social_product_access',
                'type' => 'receipt_social_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_client_create',
                'type' => 'receipt_client',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_client_edit',
                'type' => 'receipt_client',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_client_show',
                'type' => 'receipt_client',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_client_delete',
                'type' => 'receipt_client',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_client_access',
                'type' => 'receipt_client',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_client_print',
                'type' => 'receipt_client',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_client_restore',
                'type' => 'receipt_client',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_client_duplicate',
                'type' => 'receipt_client',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_client_receive_money',
                'type' => 'receipt_client',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_client_product_create',
                'type' => 'receipt_client_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_client_product_edit',
                'type' => 'receipt_client_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_client_product_show',
                'type' => 'receipt_client_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_client_product_delete',
                'type' => 'receipt_client_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_client_product_access',
                'type' => 'receipt_client_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_company_create',
                'type' => 'receipt_company',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_company_edit',
                'type' => 'receipt_company',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_company_show',
                'type' => 'receipt_company',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_company_delete',
                'type' => 'receipt_company',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_company_access',
                'type' => 'receipt_company',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_company_duplicate',
                'type' => 'receipt_company',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_company_print',
                'type' => 'receipt_company',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_company_restore',
                'type' => 'receipt_company',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'setting_access',
                'type' => 'website_setting.financial_account.country.social.police.currency.contactu.subscribe',
                'parent' => 1,
            ], 
            [
                'id'    => $i++,
                'title' => 'website_setting_create',
                'type' => 'website_setting',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'website_setting_edit',
                'type' => 'website_setting',
                'parent' => 0,
            ], 
            [
                'id'    => $i++,
                'title' => 'website_setting_access',
                'type' => 'website_setting',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'customer_create',
                'type' => 'customer',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'customer_edit',
                'type' => 'customer',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'customer_show',
                'type' => 'customer',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'customer_delete',
                'type' => 'customer',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'customer_access',
                'type' => 'customer',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'seller_managment_access',
                'type' => 'seller.commission_request',
                'parent' => 1,
            ],
            [
                'id'    => $i++,
                'title' => 'seller_create',
                'type' => 'seller',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'seller_edit',
                'type' => 'seller',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'seller_show',
                'type' => 'seller',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'seller_delete',
                'type' => 'seller',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'seller_access',
                'type' => 'seller',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'commission_request_create',
                'type' => 'commission_request',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'commission_request_edit',
                'type' => 'commission_request',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'commission_request_show',
                'type' => 'commission_request',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'commission_request_delete',
                'type' => 'commission_request',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'commission_request_access',
                'type' => 'commission_request',
                'parent' => 0,]
            ,  
            [
                'id'    => $i++,
                'title' => 'employee_create',
                'type' => 'employee',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'employee_edit',
                'type' => 'employee',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'employee_show',
                'type' => 'employee',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'employee_delete',
                'type' => 'employee',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'employee_access',
                'type' => 'employee',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'country_create',
                'type' => 'country',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'country_edit',
                'type' => 'country',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'country_show',
                'type' => 'country',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'country_delete',
                'type' => 'country',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'country_access',
                'type' => 'country',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'social_create',
                'type' => 'social',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'social_edit',
                'type' => 'social',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'social_show',
                'type' => 'social',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'social_delete',
                'type' => 'social',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'social_access',
                'type' => 'social',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'banned_phone_create',
                'type' => 'banned_phone',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'banned_phone_edit',
                'type' => 'banned_phone',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'banned_phone_show',
                'type' => 'banned_phone',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'banned_phone_delete',
                'type' => 'banned_phone',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'banned_phone_access',
                'type' => 'banned_phone',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'police_create',
                'type' => 'police',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'police_edit',
                'type' => 'police',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'police_show',
                'type' => 'police',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'police_delete',
                'type' => 'police',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'police_access',
                'type' => 'police',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'frontend_setting_access',
                'type' => 'slider.banner.home_category.quality_resposible',
                'parent' => 1,
            ],
            [
                'id'    => $i++,
                'title' => 'slider_create',
                'type' => 'slider',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'slider_edit',
                'type' => 'slider',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'slider_show',
                'type' => 'slider',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'slider_delete',
                'type' => 'slider',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'slider_access',
                'type' => 'slider',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'banner_create',
                'type' => 'banner',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'banner_edit',
                'type' => 'banner',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'banner_show',
                'type' => 'banner',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'banner_delete',
                'type' => 'banner',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'banner_access',
                'type' => 'banner',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'product_managment_access',
                'type' => 'category.product.sub_category.sub_sub_category.attribute.review',
                'parent' => 1,
            ],
            [
                'id'    => $i++,
                'title' => 'category_create',
                'type' => 'category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'category_edit',
                'type' => 'category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'category_show',
                'type' => 'category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'category_delete',
                'type' => 'category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'category_access',
                'type' => 'category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'home_category_create',
                'type' => 'home_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'home_category_edit',
                'type' => 'home_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'home_category_show',
                'type' => 'home_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'home_category_delete',
                'type' => 'home_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'home_category_access',
                'type' => 'home_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'quality_responsible_create',
                'type' => 'quality_responsible',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'quality_responsible_edit',
                'type' => 'quality_responsible',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'quality_responsible_show',
                'type' => 'quality_responsible',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'quality_responsible_delete',
                'type' => 'quality_responsible',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'quality_responsible_access',
                'type' => 'quality_responsible',
                'parent' => 0,
            ], 
            [
                'id'    => $i++,
                'title' => 'conversation_create',
                'type' => 'conversation',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'conversation_edit',
                'type' => 'conversation',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'conversation_show',
                'type' => 'conversation',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'conversation_delete',
                'type' => 'conversation',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'conversation_access',
                'type' => 'conversation',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'order_create',
                'type' => 'order',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'order_edit',
                'type' => 'order',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'order_show',
                'type' => 'order',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'order_delete',
                'type' => 'order',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'order_access',
                'type' => 'order',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'order_print',
                'type' => 'order',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_outgoing_create',
                'type' => 'receipt_outgoing',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_outgoing_edit',
                'type' => 'receipt_outgoing',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_outgoing_show',
                'type' => 'receipt_outgoing',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_outgoing_delete',
                'type' => 'receipt_outgoing',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_outgoing_restore',
                'type' => 'receipt_outgoing',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_outgoing_access',
                'type' => 'receipt_outgoing',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_outgoing_print',
                'type' => 'receipt_outgoing',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_outgoing_duplicate',
                'type' => 'receipt_outgoing',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_outgoing_product_create',
                'type' => 'receipt_outgoing_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_outgoing_product_edit',
                'type' => 'receipt_outgoing_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_outgoing_product_show',
                'type' => 'receipt_outgoing_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_outgoing_product_delete',
                'type' => 'receipt_outgoing_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_outgoing_product_access',
                'type' => 'receipt_outgoing_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_price_view_create',
                'type' => 'receipt_price_view',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_price_view_edit',
                'type' => 'receipt_price_view',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_price_view_show',
                'type' => 'receipt_price_view',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_price_view_delete',
                'type' => 'receipt_price_view',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_price_view_access',
                'type' => 'receipt_price_view',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_price_view_print',
                'type' => 'receipt_price_view',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_price_view_restore',
                'type' => 'receipt_price_view',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_price_view_product_create',
                'type' => 'receipt_price_view_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_price_view_product_edit',
                'type' => 'receipt_price_view_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_price_view_product_show',
                'type' => 'receipt_price_view_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_price_view_product_delete',
                'type' => 'receipt_price_view_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_price_view_product_access',
                'type' => 'receipt_price_view_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'excel_file_create',
                'type' => 'excel_file',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'excel_file_edit',
                'type' => 'excel_file',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'excel_file_show',
                'type' => 'excel_file',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'excel_file_delete',
                'type' => 'excel_file',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'excel_file_access',
                'type' => 'excel_file',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'product_create',
                'type' => 'product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'product_edit',
                'type' => 'product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'product_show',
                'type' => 'product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'product_delete',
                'type' => 'product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'product_access',
                'type' => 'product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'sub_category_create',
                'type' => 'sub_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'sub_category_edit',
                'type' => 'sub_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'sub_category_show',
                'type' => 'sub_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'sub_category_delete',
                'type' => 'sub_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'sub_category_access',
                'type' => 'sub_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'sub_sub_category_create',
                'type' => 'sub_sub_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'sub_sub_category_edit',
                'type' => 'sub_sub_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'sub_sub_category_show',
                'type' => 'sub_sub_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'sub_sub_category_delete',
                'type' => 'sub_sub_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'sub_sub_category_access',
                'type' => 'sub_sub_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'attribute_create',
                'type' => 'attribute',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'attribute_edit',
                'type' => 'attribute',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'attribute_show',
                'type' => 'attribute',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'attribute_delete',
                'type' => 'attribute',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'attribute_access',
                'type' => 'attribute',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'review_access',
                'type' => 'review',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'playlist_design',
                'type' => 'playlist',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'playlist_manufacturing',
                'type' => 'playlist',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'playlist_prepare',
                'type' => 'playlist',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'playlist_shipment',
                'type' => 'playlist',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'playlist_access',
                'type' => 'playlist',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'faq_management_access',
                'type' => 'faq_category.faq_question',
                'parent' => 1,
            ],
            [
                'id'    => $i++,
                'title' => 'faq_category_create',
                'type' => 'faq_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'faq_category_edit',
                'type' => 'faq_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'faq_category_show',
                'type' => 'faq_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'faq_category_delete',
                'type' => 'faq_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'faq_category_access',
                'type' => 'faq_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'faq_question_create',
                'type' => 'faq_question',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'faq_question_edit',
                'type' => 'faq_question',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'faq_question_show',
                'type' => 'faq_question',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'faq_question_delete',
                'type' => 'faq_question',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'faq_question_access',
                'type' => 'faq_question',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'mockups_managment_access',
                'type' => 'mockup.designer.design',
                'parent' => 1,
            ],
            [
                'id'    => $i++,
                'title' => 'mockup_create',
                'type' => 'mockup',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'mockup_edit',
                'type' => 'mockup',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'mockup_show',
                'type' => 'mockup',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'mockup_delete',
                'type' => 'mockup',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'mockup_access',
                'type' => 'mockup',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'designer_create',
                'type' => 'designer',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'designer_edit',
                'type' => 'designer',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'designer_show',
                'type' => 'designer',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'designer_delete',
                'type' => 'designer',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'designer_access',
                'type' => 'designer',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'design_create',
                'type' => 'design',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'design_edit',
                'type' => 'design',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'design_show',
                'type' => 'design',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'design_delete',
                'type' => 'design',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'design_access',
                'type' => 'design',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'delivery_order_create',
                'type' => 'delivery_order',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'delivery_order_edit',
                'type' => 'delivery_order',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'delivery_order_show',
                'type' => 'delivery_order',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'delivery_order_delete',
                'type' => 'delivery_order',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'delivery_order_access',
                'type' => 'delivery_order',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'delivery_managment_access',
                'type' => 'delivery_order.deliver_man',
                'parent' => 1,
            ],
            [
                'id'    => $i++,
                'title' => 'deliver_man_create',
                'type' => 'deliver_man',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'deliver_man_edit',
                'type' => 'deliver_man',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'deliver_man_show',
                'type' => 'deliver_man',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'deliver_man_delete',
                'type' => 'deliver_man',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'deliver_man_access',
                'type' => 'deliver_man',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'currency_create',
                'type' => 'currency',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'currency_edit',
                'type' => 'currency',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'currency_show',
                'type' => 'currency',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'currency_delete',
                'type' => 'currency',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'currency_access',
                'type' => 'currency',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'contactu_show',
                'type' => 'subscribe',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'contactu_delete',
                'type' => 'subscribe',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'contactu_access',
                'type' => 'subscribe',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'subscribe_delete',
                'type' => 'subscribe',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'subscribe_access',
                'type' => 'subscribe',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'hold',
                'type' => 'general',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'expense_management_access',
                'type' => 'expense_category.income_category.expense.income.expense_report',
                'parent' => 1,
            ],
            [
                'id'    => $i++,
                'title' => 'expense_category_create',
                'type' => 'expense_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'expense_category_edit',
                'type' => 'expense_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'expense_category_show',
                'type' => 'expense_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'expense_category_delete',
                'type' => 'expense_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'expense_category_access',
                'type' => 'expense_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'income_category_create',
                'type' => 'income_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'income_category_edit',
                'type' => 'income_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'income_category_show',
                'type' => 'income_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'income_category_delete',
                'type' => 'income_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'income_category_access',
                'type' => 'income_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'expense_create',
                'type' => 'expense',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'expense_edit',
                'type' => 'expense',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'expense_show',
                'type' => 'expense',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'expense_delete',
                'type' => 'expense',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'expense_access',
                'type' => 'expense',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'income_create',
                'type' => 'income',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'income_edit',
                'type' => 'income',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'income_show',
                'type' => 'income',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'income_delete',
                'type' => 'income',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'income_access',
                'type' => 'income',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'expense_report_create',
                'type' => 'expense_report',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'expense_report_edit',
                'type' => 'expense_report',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'expense_report_show',
                'type' => 'expense_report',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'expense_report_delete',
                'type' => 'expense_report',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'expense_report_access',
                'type' => 'expense_report',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'r_client_create',
                'type' => 'r_client',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'r_client_edit',
                'type' => 'r_client',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'r_client_show',
                'type' => 'r_client',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'r_client_delete',
                'type' => 'r_client',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'r_client_access',
                'type' => 'r_client',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'r_branch_create',
                'type' => 'r_branch',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'r_branch_edit',
                'type' => 'r_branch',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'r_branch_show',
                'type' => 'r_branch',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'r_branch_delete',
                'type' => 'r_branch',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'r_branch_access',
                'type' => 'r_branch',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_branch_managment_access',
                'type' => 'r_client.r_branch.receipt_branch.receipt_branch_product',
                'parent' => 1,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_branch_create',
                'type' => 'receipt_branch',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_branch_edit',
                'type' => 'receipt_branch',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_branch_show',
                'type' => 'receipt_branch',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_branch_delete',
                'type' => 'receipt_branch',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_branch_access',
                'type' => 'receipt_branch',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_branch_print',
                'type' => 'receipt_branch',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_branch_restore',
                'type' => 'receipt_branch',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_branch_duplicate',
                'type' => 'receipt_branch',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_branch_receive_money',
                'type' => 'receipt_branch',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_branch_product_create',
                'type' => 'receipt_branch_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_branch_product_edit',
                'type' => 'receipt_branch_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_branch_product_show',
                'type' => 'receipt_branch_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_branch_product_delete',
                'type' => 'receipt_branch_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_branch_product_access',
                'type' => 'receipt_branch_product',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'employee_managment_access',
                'type' => 'employee.financial_category.employee_financial',
                'parent' => 1,
            ],
            [
                'id'    => $i++,
                'title' => 'financial_category_create',
                'type' => 'financial_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'financial_category_edit',
                'type' => 'financial_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'financial_category_show',
                'type' => 'financial_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'financial_category_delete',
                'type' => 'financial_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'financial_category_access',
                'type' => 'financial_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'employee_financial_create',
                'type' => 'employee_financial',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'employee_financial_edit',
                'type' => 'employee_financial',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'employee_financial_show',
                'type' => 'employee_financial',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'employee_financial_delete',
                'type' => 'employee_financial',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'employee_financial_access',
                'type' => 'employee_financial',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'material_create',
                'type' => 'material',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'material_edit',
                'type' => 'material',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'material_show',
                'type' => 'material',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'material_delete',
                'type' => 'material',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'material_access',
                'type' => 'material',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'financial_account_create',
                'type' => 'financial_account',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'financial_account_edit',
                'type' => 'financial_account',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'financial_account_show',
                'type' => 'financial_account',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'financial_account_delete',
                'type' => 'financial_account',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'financial_account_access',
                'type' => 'financial_account',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'profile_password_edit',
                'type' => 'general',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'transfer_receipts',
                'type' => 'general',
                'parent' => 0,
            ], 
            [
                'id'    => $i++,
                'title' => 'download_receipts',
                'type' => 'general',
                'parent' => 0,
            ], 
            [
                'id'    => $i++,
                'title' => 'statistics_receipts',
                'type' => 'general',
                'parent' => 0,
            ], 
            [
                'id'    => $i++,
                'title' => 'material_income',
                'type' => 'material',
                'parent' => 0,
            ], 
            [
                'id'    => $i++,
                'title' => 'material_expense',
                'type' => 'material',
                'parent' => 0,
            ], 
            [
                'id'    => $i++,
                'title' => 'supplied',
                'type' => 'general',
                'parent' => 0,
            ], 
            [
                'id'    => $i++,
                'title' => 'done',
                'type' => 'general',
                'parent' => 0,
            ], 
            [
                'id'    => $i++,
                'title' => 'soft_delete',
                'type' => 'general',
                'parent' => 0,
            ], 
            [
                'id'    => $i++,
                'title' => 'receipt_social_view_products',
                'type' => 'receipt_social',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_social_add_product',
                'type' => 'receipt_social',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_social_edit_product',
                'type' => 'receipt_social',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_social_delete_product',
                'type' => 'receipt_social',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_client_view_products',
                'type' => 'receipt_client',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_client_add_product',
                'type' => 'receipt_client',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_client_edit_product',
                'type' => 'receipt_client',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_client_delete_product',
                'type' => 'receipt_client',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_outgoing_view_products',
                'type' => 'receipt_outgoing',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_outgoing_add_product',
                'type' => 'receipt_outgoing',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_outgoing_edit_product',
                'type' => 'receipt_outgoing',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_outgoing_delete_product',
                'type' => 'receipt_outgoing',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_price_view_view_products',
                'type' => 'receipt_price_view',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_price_view_add_product',
                'type' => 'receipt_price_view',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_price_view_edit_product',
                'type' => 'receipt_price_view',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_price_view_delete_product',
                'type' => 'receipt_price_view',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_branch_view_products',
                'type' => 'receipt_branch',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_branch_add_product',
                'type' => 'receipt_branch',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_branch_edit_product',
                'type' => 'receipt_branch',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'receipt_branch_delete_product',
                'type' => 'receipt_branch',
                'parent' => 0,
            ],
        ];

        Permission::insert($permissions);
    }
}
